### ISSUE TITLE
Rewards are triggered without the required playing time being achieved.

### ISSUE THREAD

**Issue by SgtChrisCross** [MiniDigger/OnlineTime#4]
I have on my server 183 hours playtime and if i join the server i get every reward up to 300hours.

```
message: "&aSpielzeit &8&l>&r %p% &8&l>&r &e%d% &rTage &e%h% &rStunden &e%m% &rMinuten und &e%s% &rSekunden."
show-reward-notification: true
check-period: "5M"
rewards:
  1:
     message: "&aSpielzeit &8&l>&r 1 Stunden Belohnung"
     time: "1H"
     commands:
       - "cc give v Ungewöhnlich 1 %p%"
  3:
     message: "&aSpielzeit &8&l>&r 3 Stunden Belohnung"
     time: "3H"
     commands:
       - "eco give %p% 15"
  5:
     message: "&aSpielzeit &8&l>&r 5 Stunden Belohnung"
     time: "5H"
     commands:
       - "cc give v Ungewöhnlich 1 %p%"
       - "eco give %p% 10"
  10:
     message: "&aSpielzeit &8&l>&r 10 Stunden Belohnung"
     time: "10H"
     commands:
       - "cc give v Selten 1 %p%"
       - "eco give %p% 10"
       - "broadcast &f%p% hat 10 Spielstunden erreicht!"
  15:
     message: "&aSpielzeit &8&l>&r 15 Stunden Belohnung"
     time: "15H"
     commands:
       - "cc give v Ungewöhnlich 1 %p%"
       - "eco give %p% 15"
  20:
     message: "&aSpielzeit &8&l>&r 20 Stunden Belohnung"
     time: "20H"
     commands:
       - "cc give v Selten 1 %p%"
       - "eco give %p% 20"
  25:
     message: "&aSpielzeit &8&l>&r 25 Stunden Belohnung"
     time: "1D1H"
     commands:
       - "cc give v Ungewöhnlich 1 %p%"
       - "eco give %p% 20"
       - "broadcast &f%p% hat 25 Spielstunden erreicht!"
  30:
     message: "&aSpielzeit &8&l>&r 30 Stunden Belohnung"
     time: "1D6H"
     commands:
       - "cc give v Episch 1 %p%"
       - "eco give %p% 50"
  35:
     message: "&aSpielzeit &8&l>&r 35 Stunden Belohnung"
     time: "1D11H"
     commands:
       - "cc give v Ungewöhnlich 1 %p%"
       - "eco give %p% 20"
  40:
     message: "&aSpielzeit &8&l>&r 40 Stunden Belohnung"
     time: "1D16H"
     commands:
       - "cc give v Selten 1 %p%"
       - "eco give %p% 20"
  45:
     message: "&aSpielzeit &8&l>&r 45 Stunden Belohnung"
     time: "1D21H"
     commands:
       - "cc give v Ungewöhnlich 1 %p%"
       - "eco give %p% 20"
  50:
     message: "&aSpielzeit &8&l>&r 50 Stunden Belohnung"
     time: "2D2H"
     commands:
       - "cc give v Selten 2 %p%"
       - "eco give %p% 75"
       - "broadcast &f%p% hat 50 Spielstunden erreicht!"
  55:
     message: "&aSpielzeit &8&l>&r 55 Stunden Belohnung"
     time: "2D7H"
     commands:
       - "cc give v Episch 1 %p%"
       - "eco give %p% 20"
  60:
     message: "&aSpielzeit &8&l>&r 60 Stunden Belohnung"
     time: "2D12H"
     commands:
       - "cc give v Ungewöhnlich 1 %p%"
       - "eco give %p% 20"
  65:
     message: "&aSpielzeit &8&l>&r 65 Stunden Belohnung"
     time: "2D17H"
     commands:
       - "cc give v Selten 1 %p%"
       - "eco give %p% 20"
  70:
     message: "&aSpielzeit &8&l>&r 70 Stunden Belohnung"
     time: "2D22H"
     commands:
       - "cc give v Selten 1 %p%"
       - "eco give %p% 20"
  75:
     message: "&aSpielzeit &8&l>&r 75 Stunden Belohnung"
     time: "3D3H"
     commands:
       - "cc give v Episch 2 %p%"
       - "eco give %p% 100"
  80:
     message: "&aSpielzeit &8&l>&r 80 Stunden Belohnung"
     time: "3D8H"
     commands:
       - "cc give v Ungewöhnlich 1 %p%"
       - "eco give %p% 20"
  85:
     message: "&aSpielzeit &8&l>&r 85 Stunden Belohnung"
     time: "3D13H"
     commands:
       - "cc give v Ungewöhnlich 1 %p%"
       - "eco give %p% 20"
  90:
     message: "&aSpielzeit &8&l>&r 90 Stunden Belohnung"
     time: "3D18H"
     commands:
       - "cc give v Selten 1 %p%"
       - "eco give %p% 20"
  95:
     message: "&aSpielzeit &8&l>&r 95 Stunden Belohnung"
     time: "3D23H"
     commands:
       - "cc give v Episch 1 %p%"
       - "eco give %p% 20"
  100:
     message: "&aSpielzeit &8&l>&r 100 Stunden Belohnung"
     time: "4D4H"
     commands:
       - "cc give v Legendär 1 %p%"
       - "eco give %p% 250"
       - "broadcast &f%p% hat 100 Spielstunden erreicht!"
  110:
     message: "&aSpielzeit &8&l>&r 110 Stunden Belohnung"
     time: "4D14H"
     commands:
       - "cc give v Ungewöhnlich 2 %p%"
       - "eco give %p% 30"
  120:
     message: "&aSpielzeit &8&l>&r 120 Stunden Belohnung"
     time: "5D"
     commands:
       - "cc give v Selten 2 %p%"
       - "eco give %p% 30"
  130:
     message: "&aSpielzeit &8&l>&r 130 Stunden Belohnung"
     time: "5D10H"
     commands:
       - "cc give v Episch 1 %p%"
       - "eco give %p% 30"
  140:
     message: "&aSpielzeit &8&l>&r 140 Stunden Belohnung"
     time: "5D20H"
     commands:
       - "cc give v Ungewöhnlich 2 %p%"
       - "eco give %p% 30"
  150:
     message: "&aSpielzeit &8&l>&r 150 Stunden Belohnung"
     time: "6D6H"
     commands:
       - "cc give v Ungewöhnlich 5 %p%"
       - "eco give %p% 350"
       - "broadcast &f%p% hat 150 Spielstunden erreicht!"
  160:
     message: "&aSpielzeit &8&l>&r 160 Stunden Belohnung"
     time: "6D16H"
     commands:
       - "cc give v Selten 1 %p%"
       - "eco give %p% 30"
  170:
     message: "&aSpielzeit &8&l>&r 170 Stunden Belohnung"
     time: "7D2H"
     commands:
       - "cc give v Episch 1 %p%"
       - "eco give %p% 30"
  180:
     message: "&aSpielzeit &8&l>&r 180 Stunden Belohnung"
     time: "7D12H"
     commands:
       - "cc give v Ungewöhnlich 2 %p%"
       - "eco give %p% 30"
  190:
     message: "&aSpielzeit &8&l>&r 190 Stunden Belohnung"
     time: "7D22H"
     commands:
       - "cc give v Selten 2 %p%"
       - "eco give %p% 30"
  200:
     message: "&aSpielzeit &8&l>&r 200 Stunden Belohnung"
     time: "8D8H"
     commands:
       - "cc give v Legendär 2 %p%"
       - "eco give %p% 500"
       - "broadcast &f%p% hat 200 Spielstunden erreicht!"
  210:
     message: "&aSpielzeit &8&l>&r 210 Stunden Belohnung"
     time: "8D18H"
     commands:
       - "cc give v Episch 2 %p%"
       - "eco give %p% 40"
  220:
     message: "&aSpielzeit &8&l>&r 220 Stunden Belohnung"
     time: "9D4H"
     commands:
       - "cc give v Selten 2 %p%"
       - "eco give %p% 40"
  230:
     message: "&aSpielzeit &8&l>&r 230 Stunden Belohnung"
     time: "9D14H"
     commands:
       - "cc give v Ungewöhnlich 3 %p%"
       - "eco give %p% 40"
  240:
     message: "&aSpielzeit &8&l>&r 240 Stunden Belohnung"
     time: "10D"
     commands:
       - "cc give v Ungewöhnlich 3 %p%"
       - "eco give %p% 40"
  250:
     message: "&aSpielzeit &8&l>&r 250 Stunden Belohnung"
     time: "10D10H"
     commands:
       - "cc give v Selten 5 %p%"
       - "eco give %p% 750"
       - "broadcast &f%p% hat 250 Spielstunden erreicht!"
  260:
     message: "&aSpielzeit &8&l>&r 260 Stunden Belohnung"
     time: "10D20H"
     commands:
       - "cc give v Episch 2 %p%"
       - "eco give %p% 40"
  270:
     message: "&aSpielzeit &8&l>&r 270 Stunden Belohnung"
     time: "11D6H"
     commands:
       - "cc give v Selten 2 %p%"
       - "eco give %p% 40"
  280:
     message: "&aSpielzeit &8&l>&r 280 Stunden Belohnung"
     time: "11D16H"
     commands:
       - "cc give v Episch 2 %p%"
       - "eco give %p% 40"
  290:
     message: "&aSpielzeit &8&l>&r 290 Stunden Belohnung"
     time: "12D2H"
     commands:
       - "cc give v Legendär 3 %p%"
       - "eco give %p% 1000"
  300:
     message: "&aSpielzeit &8&l>&r 300 Stunden Belohnung"
     time: "12D12H"
     commands:
       - "lp user %p% parent set ehrenmitglied"
       - "broadcast &f%p% hat 300 Spielstunden erreicht und erhält den &6Ehrenmitglied &fRang!"
```
